AWSTemplateFormatVersion: 2010-09-09
Description: DNS Resolution - Example

Parameters:
  PrivateHostedZoneName:
    Type: String
    Description: Private Hosted Zone Name (for External Connectivity VPC resolution) - specificy either this value for PrivateHostedZoneId
    Default: "EMPTY"
  PrivateHostedZoneId:
    Type: String
    Description: Private Hosted Zone ID (for External Connectivity VPC resolution) - specificy either this value for PrivateHostedZoneName
    Default: "EMPTY"
  CustomDomainName:
    Type: String
    Description: Custom Domain Name (VPC Lattice service)
  VPCLatticeDomainName:
    Type: String
    Description: VPC Lattice service generated Domain Name
  VPCLatticeHostedZoneId:
    Type: String
    Description: VPC Lattice service generated Hosted Zone ID
  NLBDomainName:
    Type: String
    Description: Network Load Balancer domain name
  NLBHostedZoneId:
    Type: String
    Description: Network Load Balancer hosted zone ID
  VpcId:
    Type: String
    Description: VPC ID (Ingress VPC)
  PublicHostedZone:
    Type: String
    Description: Amazon Route 53 Public Hosted Zone ID

Conditions:
  CreatePrivateHostedZone: !And
    - !Not [!Equals [!Ref PrivateHostedZoneName, "EMPTY"]]
    - !Equals [!Ref PrivateHostedZoneId, "EMPTY"]

Resources:
  # ---------- PUBLIC RESOLUTION ----------
  PublicALIASRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PublicHostedZone
      Name: !Ref CustomDomainName
      Type: A
      AliasTarget:
        DNSName: !Ref NLBDomainName
        HostedZoneId: !Ref NLBHostedZoneId
        EvaluateTargetHealth: false

  # ---------- VPC RESOLUTION ----------
  VPCHostedZone:
    Condition: CreatePrivateHostedZone
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref PrivateHostedZoneName
      VPCs:
        - VPCId: !Ref VpcId
          VPCRegion: !Ref "AWS::Region"
  
  VpcALIASRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !If
        - CreatePrivateHostedZone
        - !Ref VPCHostedZone
        - !Ref PrivateHostedZoneId
      Name: !Ref CustomDomainName
      Type: A
      AliasTarget:
        HostedZoneId: !Ref VPCLatticeHostedZoneId
        DNSName: !Ref VPCLatticeDomainName
        EvaluateTargetHealth: false